### PR TITLE
perf(elasticsearch): use bulk capability to improve performances

### PR DESCRIPTION
**Pull request by Thenkei**

### CODE REVIEW

**Comment by Thenkei** [comment]
Task linked: [CU-860t03qmz Story #2.4 - Create records - 3 pts](https://app.clickup.com/t/860t03qmz)

**Comment by Thenkei** [comment]
Task linked: [CU-860t03qhd Story #2.1 - Update records - 3 pts](https://app.clickup.com/t/860t03qhd)

**Comment by Thenkei** [comment]
Task linked: [CU-860t03qjf Story #2.2 - Delete records - 2 pts](https://app.clickup.com/t/860t03qjf)

**Review by realSpok — APPROVED** [review]
- ✅  Code review
  - ✅  Use pure functions when possible
  - ✅  Performance concerns
  - ✅  Security concerns
  - ✅  The PR tackle one subject only
- ✅Automatic tests
  - ⤬  Unit tests
  - ✅  Integration tests
- ✅ Manual tests
  -  ✅  Test the functionality
  -  ✅  Test error cases
- ✅  PR title
- ✅  Destination branch
- ✅  PR linked to the clickup task

**Pull request merged**
