### PR TITLE
feat(define-enum): create a plugin for creating enum fields over an existing field

### PR DESCRIPTION
**Pull request by Thenkei**

### CODE REVIEW

**Comment by Aralun** [comment]
Hey there, kll from the community here =)

I'm getting a TS2322 error on the `dependencies`:
image

And possibly related, a TS2536 on the index access:
image

I'm also not getting any typing on the `field` in the options. Probably related to the above though.

**Comment by Thenkei** [comment]
@Aralun what version of `@forestadmin/datasource-customizer` and `@forestadmin/datasource-toolkit` are you using ?

**Comment by Aralun** [comment]
Those are imported from @forestadmin/agent 1.40.1, should I add them separately?

**Comment by Aralun** [comment]
Ah, according to my yarn.lock:
    "@forestadmin/datasource-customizer" "1.44.3"
    "@forestadmin/datasource-toolkit" "1.33.0"

**Pull request merged**
